const Questions = {
    lvls: 5,
    lvl1: [["póki co", "puki co"],
            ["wziąć", "wziąść", "wziąźć"],
            ["jabłko", "jabko"],
            ["pojedynczy", "pojedyńczy"],
            ["poszedłem", "poszłem"],
            ["w ogóle", "wogóle"],
            ["zwierzę", "zwierze"],
            ["parę groszy", "pare groszy"],
            ["proszę", "prosze"],
            ["waha", "wacha"]],
    lvl2: [["w każdym razie", "w każdym bądź razie"],
            ["wielką literą", "z wielkiej litery"],
            ["liczba gatunków", "ilość gatunków"],
            ["stąd", "z tąd", "stond"],
            ["na pewno", "napewno"],
            ["tylny", "tylni"],
            ["książę z bajki", "książe z bajki"],
            ["po prostu", "poprostu"],
            ["z powrotem", "spowrotem"],
            ["można by", "możnaby"]],
    lvl3: [["dużą literą", "z dużej litery"],
            ["pełnić funkcję", "pełnić rolę"],
            ["stamtąd", "z tamtąd"],
            ["w głąb", "wgłąb", "wgłomb"],
            ["naprzeciwko", "na przeciwko"],
            ["zrobiłbym", "zrobił bym"],
            ["imię", "imie"],
            ["na co dzień", "na codzień", "nacodzień"],
            ["co najmniej", "conajmniej"],
            ["zresztą co cię to obchodzi?", "z resztą co cię to obchodzi?"]],
    lvl4: [["linii najmniejszego oporu", "najmniejszej lini oporu"],
            ["dwa tysiące ósmy", "dwutysięczny ósmy"],
            ["mogłoby", "mogło by"],
            ["pszenica", "przenica"],
            ["łańcuszek na szyi", "łańcuszek na szyji"],
            ["sprzed", "z przed"],
            ["znad", "z nad"],
            ["nie lada sztuka", "nielada sztuka"],
            ["naprawdę", "na prawdę", "naprawde", "na prawde"],
            ["kosztować mniej", "kosztować taniej"]],
    lvl5: [["oddziałujący", "oddziaływujący"],
            ["na skutek", "na wskutek"],
            ["uznać za", "uznać jako"],
            ["żądać", "rządać"],
            ["ludziom", "ludzią"],
            ["rządzi", "żądzi"],
            ["wąchać", "wąhać"],
            ["spadać", "spadać w dół"],
            ["20-lecie", "20-sto lecie"],
            ["dwuipółletni", "dwu i pół letni"]]
}
